version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
